---
- name: Setup EC2 instance
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      shell: |
        until yum -y update; do
          echo "Waiting for yum lock to be released"
          sleep 30
        done
      register: update_result
      retries: 5
      delay: 30
      until: update_result.rc == 0

    - name: Install SSM Agent
      shell: |
        until yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm; do
          echo "Waiting for yum lock to be released"
          sleep 30
        done
      register: install_ssm
      retries: 5
      delay: 30
      until: install_ssm.rc == 0

    - name: Install CloudWatch Agent
      shell: |
        until yum -y install https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm; do
          echo "Waiting for yum lock to be released"
          sleep 30
        done
      register: install_cloudwatch
      retries: 5
      delay: 30
      until: install_cloudwatch.rc == 0

    - name: Start CloudWatch Agent
      command: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a start

    - name: Check CloudWatch Agent Status
      command: sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status

    - name: Install AWS Inspector
      shell: |
        curl -O https://inspector-agent.amazonaws.com/linux/latest/install
        sudo bash install

    - name: Install Docker
      shell: |
        until yum -y install docker; do
          echo "Waiting for yum lock to be released"
          sleep 30
        done

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: yes
